-- AGREGAR COLUMNAS PARA BCF-02 SESSION MANAGER
ALTER TABLE users ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS country TEXT DEFAULT 'MX';
ALTER TABLE users ADD COLUMN IF NOT EXISTS timezone TEXT DEFAULT 'America/Chihuahua';
ALTER TABLE users ADD COLUMN IF NOT EXISTS travel_city TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS travel_until DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_channel TEXT DEFAULT 'telegram';
ALTER TABLE users ADD COLUMN IF NOT EXISTS exclusive_mode TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS exclusive_data JSONB;

-- ACTUALIZAR EL USUARIO JJR
UPDATE users SET
    city = 'Chihuahua',
    country = 'MX',
    timezone = 'America/Chihuahua'
WHERE id = '8d0f6704-521b-4913-801b-3bc0b6ea9720';
