app = "koda-platform"
primary_region = "iad"

[env]
  PORT = "3000"
  OPENWEATHER_API_KEY = ""
  EXCHANGE_RATE_API_KEY = ""
  SPORTRADAR_API_KEY = ""
  SPOTIFY_CLIENT_ID = ""
  SPOTIFY_CLIENT_SECRET = ""

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[regions]]
  region = "iad"

[[regions]]
  region = "qro"
